name: xdm-snap
base: core22
version: '8.0.26'
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64 
package-repositories:
  - type: apt
    ppa: tomtomtom/yt-dlp
    
apps:
  xdm-snap: 
    command: opt/xdman/xdm-app
    extensions: [gnome]
    environment: 
       GTK_USE_PORTAL: '1'
    desktop: usr/share/applications/xdm-app.desktop
    plugs:
      - home
      - network
      - network-bind
      - network-status
      - raw-usb
      - browser-support
      - process-control
      - audio-playback
      - removable-media
      - unity7
      - screen-inhibit-control

parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm/releases/download/8.0.26/xdman_gtk_8.0.26_amd64.deb
    plugin: dump
    stage-packages:
      - curl
      - yt-dlp
      - ffmpeg 
      - hicolor-icon-theme
