name: xdm-snap
base: core22
version: '8.0.25-beta'
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64

plugs:
  shmem:
    interface: shared-memory
    private: true

        
apps:
  xdm-snap:
    command: opt/xdman/xdm-app
    extensions: [gnome]
    common-id: org.xdm.snap 
    environment:
      GTK_USE_PORTAL: 1
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - shmem
      - home
      - network-status
      - network
      - network-bind
      - network-observe
      - raw-usb
      - process-control
      - browser-support
      - pulseaudio
      - audio-playback
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
        
    
parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm-experimental-binaries/releases/download/8.0.25-beta/xdman_gtk_8.0.25_amd64.deb
    plugin: dump
    stage-packages:
      - hicolor-icon-theme
    
    stage-snaps:
      - yt-dlp/latest/stable
      - ffmpeg/latest/edge
      - curl/latest/stable
      
    
      
     
  
      
      
      
      
    
      
   
  
  
      
    
       
  
