name: xdm-snap
base: core20
version: '8.0.25'
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    run-on: amd64    


layout:
  /opt/xdman/xdm-app:
     symlink: $SNAP_DATA/opt/xdman
     
            
apps:
  xdm-snap: 
    command: opt/xdman/xdm-app
    extensions: [gnome-3-38]
    common-id: org.xdm.snap 
    plugs:
      - home
      - network-status
      - network
      - network-bind
      - network-observe
      - raw-usb
      - process-control
      - browser-support
      - pulseaudio
      - audio-playback
      - optical-drive
      - removable-media
      - unity7
      - screen-inhibit-control
 
plugs:
  gnome-3-38-2004:
    default-provider: gnome-3-38-2004
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/sounds
    
parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm-experimental-binaries/releases/download/8.0.25-beta/xdman_gtk_8.0.25_amd64.deb
    plugin: dump
    stage-packages:
      - hicolor-icon-theme
   
  
    
   
    
    
      
    
      
     
  
      
      
      
      
    
      
   
  
  
      
    
       
  
