name: xdm-snap
base: core22
adopt-info: xdm-snap
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
#layout:
  #/usr/lib/xdm:
    #symlink: $SNAP/usr/lib/xdm

apps:
  xdm-snap:
    command: opt/xdman/xdman
    extensions: [gnome]
    common-id: org.xdm.snap
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - audio-playback
      - gsettings
      - network-status
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm.git
    plugin: nil   
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags)
    #VER="$(git ls-remote --tags https://github.com/subhra74/xdm.git | \
    #sed 's;^.*/v;;' | sort -t. -k 1,1n -k 2,2n -k 3,3n | tail -1)"
    #curl -LO https://github.com/subhra74/xdm/releases/download/v${VER}/xdm-setup-${VER}.tar.xz 
    #https://github.com/transmission/transmission/releases/download/v${VER}/transmission-${VER}.tar.xz
    #https://github.com/subhra74/xdm/releases/download/7.2.11/xdm-setup-7.2.11.tar.xz 
    build-packages:
      - curl
      - build-essential
      - make
      - git
      - autotools-dev
      - automake
      - autoconf
      - autopoint
      - libtool
      - libtool-bin
          
    override-build:
      craftctl default
      curl -LO https://github.com/subhra74/xdm/releases/download/7.2.11/xdm-setup-7.2.11.tar.xz 
      tar xf xdm-setup-7.2.11.tar.xz
      cd xdm-setup-7.2.11.tar
      ./install.sh 
      
      
    
       
  
