name: xdm-snap
base: core22
adopt-info: xdm-snap
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /opt/xdman/xdm-app:
    symlink: $SNAP/opt/xdman/xdm-app

apps:
  xdm-snap:
    command: opt/xdman/xdm-app
    extensions: [gnome]
    common-id: org.xdm.snap
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - audio-playback
      - gsettings
      - network-status
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm-experimental-binaries.git    
    plugin: dump  
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags) 
      VER=$(git describe --tags)
      curl -LO https://github.com/subhra74/xdm-experimental-binaries/releases/download/${VER}/xdman_gtk_${VER}_amd64.deb
  #https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/refs/tags/${VER}.tar.gz
  #https://github.com/subhra74/xdm-experimental-binaries/releases/download/8.0.25-beta/xdman_gtk_8.0.25_amd64.deb
    build-packages:
      - curl
      - build-essential
      - git
      - zstd
      
   
  
  
      
    
       
  
