name: xdm-snap
base: core22
version: '8.0.25-beta'
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
package-repositories:
  - type: apt
    ppa: tomtomtom/yt-dlp   
          
slots:
  dbus:
    interface: dbus
    bus: session
    name: com.ss.xdman        
        
apps:
  xdm-snap:
    command: opt/xdman/xdm-app
    extensions: [gnome]
    common-id: org.xdm.snap 
    environment:
      GTK_USE_PORTAL: 1
    plugs:
      - home
      - audio-playback
      - network-status
      - network
      - network-bind
      - network-observe
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
            
parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm-experimental-binaries/releases/download/8.0.25-beta/xdman_gtk_8.0.25_amd64.deb
    plugin: dump  
    override-pull: |
      set -eu
      craftctl default
      rm -rf usr/bin/xdman usr/share/applications/xdm-app.desktop
     
    stage-packages:
      - yt-dlp
      - curl
      - wget
      - aria2
      - axel
      - libaria2-0
     
  #xdm:
    #source: https://github.com/subhra74/xdm-experimental-binaries.git
    #plugin: nil
    #override-pull: |
      #craftctl default
      #craftctl set version=$(git describe --abbrev=0)
      
      
      
      
      
    
      
   
  
  
      
    
       
  
