name: xdm-snap
base: core22
version: '8.0.25'
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
package-repositories:
  - type: apt
    ppa: tomtomtom/yt-dlp


plugs:
  shmem:
    interface: shared-memory
    private: true
    
apps:
  xdm-snap: 
    command: /opt/xdman/xdm-app $
    extensions: [gnome]
    environment:
      GTK_USE_PORTAL: 1
    common-id: org.xdm.snap 
    plugs:
      - home
      - network
      - shmem
      - process-control
      - browser-support
      - pulseaudio
      - audio-playback
      - removable-media
      - unity7
      - screen-inhibit-control
 

parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm-experimental-binaries/releases/download/8.0.25-beta/xdman_gtk_8.0.25_amd64.deb
    plugin: dump
    stage-packages:
      - hicolor-icon-theme
      - wget
      - curl
      - yt-dlp
      - ffmpeg
      - libgtk-3-0
      - libc6
      - libgssapi-krb5-2
      - libicu70
      - libssl3
      - libstdc++6
      - zlib1g
      - libgcc-s1
      
  
    
   
    
    
      
    
      
     
  
      
      
      
      
    
      
   
  
  
      
    
       
  
