name: xdm-snap
base: core22
version: 'Latest'
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /usr/xdman/xdman:
    symlink: $SNAP/usr/xdman/xdman

apps:
  xdm-snap:
    command: usr/xdman/xdman
    extensions: [gnome]
    common-id: org.xdm.snap
    plugs:
      - home
      - audio-playback
      - gsettings
      - network-status
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
            
parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm/releases/download/7.2.11/xdm-setup-7.2.11.tar.xz 
    plugin: dump  
    build-packages:
      - curl
      - build-essential
      - git
      
    override-build: |
      set -eu
      craftctl default
      ./install.sh
      rm -rf usr/bin/xdman
     
      
      
      
      
      
    
      
   
  
  
      
    
       
  
