name: xdm-snap
base: core22
version: '8.0.25'
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /opt/xdman/xdm-app:
    symlink: $SNAP/opt/xdman/xdm-app
   
plugs:
  shmem:
    interface: shared-memory
    private: true
    
apps:
  xdm-snap: 
    command: opt/xdman/xdm-app
    extensions: [gnome]
    common-id: org.xdm.snap 
    plugs:
      - home
      - network
      - shmem
      - process-control
      - browser-support
      - pulseaudio
      - audio-playback
      - removable-media
      - unity7
 

parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm-experimental-binaries/releases/download/8.0.25-beta/xdman_gtk_8.0.25_amd64.deb
    plugin: dump
    stage-packages:
      - hicolor-icon-theme
      - wget
      - curl
      - libnettle8
      - libcrypto++8
      - libhogweed6
      - libx264-163
    stage-snaps:
      - ffmpeg/latest/edge
      - yt-dlp/latest/stable
      
   
  
    
   
    
    
      
    
      
     
  
      
      
      
      
    
      
   
  
  
      
    
       
  
