name: xdm-snap
base: core22
adopt-info: xdm-snap
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /opt/xdman/xdm-app:
    symlink: $SNAP/opt/xdman/xdm-app

apps:
  xdm-snap:
    command: opt/xdman/xdm-app
    daemon: simple
    extensions: [gnome]
    common-id: org.xdm.snap
    environment:
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - audio-playback
      - gsettings
      - network-status
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm-experimental-binaries.git    
    plugin: nil 
    override-pull:
      craftctl default
      curl -LO https://github.com/subhra74/xdm-experimental-binaries/releases/download/8.0.25-beta/xdman_gtk-8.0.25-1-x86_64.pkg.tar.zst
    build-packages:
      - curl
      - build-essential
      - make
      - git
      - debianutils
      - debian-goodies
      - debhelper
      - apt
      - dpkg
      - autotools-dev
      - automake
      - autoconf
      - autopoint
      - libtool
      - libtool-bin
    override-build:
      craftctl default
      tar -xf xdman_gtk-8.0.25-1-x86_64.pkg.tar.zst    
  
      
    
       
  
