name: xdm-snap
base: core22
version: '8.0.25'
summary: XDM Is Free and Advanced Download Manger for Linux
description: |
  XDM Is a powerful Free and Advanced Download Manger For Linux supporting several filetypes and contents..
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /opt/xdman/xdm-app:
    symlink: $SNAP/opt/xdman/xdm-app

plugs:
  shmem:
    interface: shared-memory
    private: true

        
apps:
  xdm-snap:
    command: opt/xdman/xdm-app
    extensions: [gnome]
    common-id: org.xdm.snap 
    plugs:
      - shmem
      - home
      - network-status
      - network
      - network-bind
      - network-observe
      - raw-usb
      - process-control
      - browser-support
      - pulseaudio
      - audio-playback
      - optical-drive
      - removable-media
      - unity7
      - screen-inhibit-control
        
    
parts:
  xdm-snap:
    source: https://github.com/subhra74/xdm-experimental-binaries/releases/download/8.0.25-beta/xdman_gtk_8.0.25_amd64.deb
    plugin: dump
    override-pull: |
      craftctl default
      rm -rf /opt/xdman/xdm-app.desktop /usr/share/applications/xdm-app.desktop /usr/bin/xdman
    stage-packages:
      - hicolor-icon-theme
      - glibc-source
     
    stage-snaps:
      - yt-dlp/latest/stable
      - dotnet-runtime-60/latest/stable
           
    
    
      
    
      
     
  
      
      
      
      
    
      
   
  
  
      
    
       
  
